# Generated by Django 4.1.4 on 2023-06-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='where',
            field=models.CharField(max_length=40),
        ),
    ]
