# Generated by Django 4.1.4 on 2023-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0004_stuff_active_alter_stuff_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
