# Generated by Django 4.1.4 on 2023-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0005_shop_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprecord',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
