# Generated by Django 4.1.4 on 2023-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0006_shoprecord_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
