# Generated by Django 4.1.4 on 2023-06-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0007_alter_stuff_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='frequency',
            new_name='frequencyv2',
        ),
    ]
