# Generated by Django 4.1.4 on 2023-06-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0008_rename_frequency_stuff_frequencyv2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='frequencyv2',
            new_name='frequency',
        ),
    ]
