# Generated by Django 4.1.4 on 2023-06-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0009_rename_frequencyv2_stuff_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoprecord',
            old_name='updated_at',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='shoprecord',
            old_name='created_at',
            new_name='done_on',
        ),
        migrations.RenameField(
            model_name='stuffrecord',
            old_name='updated_at',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='stuffrecord',
            old_name='created_at',
            new_name='done_on',
        ),
    ]
