# Generated by Django 4.1.4 on 2023-06-16 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0010_rename_updated_at_shoprecord_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='last_done',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
