# Generated by Django 4.1.4 on 2023-06-18 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0011_stuff_last_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffrecord',
            name='done_on_v2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
