# Generated by Django 4.1.4 on 2023-06-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0012_stuffrecord_done_on_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuffrecord',
            name='done_on_v2',
        ),
    ]
