# Generated by Django 4.1.4 on 2023-06-19 14:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bc', '0014_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRecords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('taken_on', models.DateField(default=datetime.date.today)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
