# Generated by Django 4.1.4 on 2023-07-07 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0016_rename_vacationrecords_vacationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprecord',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shoprecord',
            name='done_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stuffrecord',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stuffrecord',
            name='done_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='month',
            field=models.IntegerField(choices=[(1, 'JAN'), (2, 'FEB'), (3, 'MAR'), (4, 'APR'), (5, 'MAY'), (6, 'JUN'), (7, 'JUL'), (8, 'AUG'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DEC')], default=7),
        ),
    ]
