# Generated by Django 4.1.4 on 2023-07-07 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0018_alter_stuffrecord_done_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprecord',
            name='done_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
