# Generated by Django 4.1.4 on 2023-07-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0019_alter_shoprecord_done_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffrecord',
            name='reduction',
            field=models.FloatField(default=1),
        ),
    ]
