# Generated by Django 4.1.4 on 2023-07-09 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0020_stuffrecord_reduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('what', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
