# Generated by Django 4.1.4 on 2023-07-09 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0021_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='date',
            new_name='when',
        ),
        migrations.AddField(
            model_name='setting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='yad',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
